"""Retype raw BSS arrays while preserving upstream's existing typed storage."""
import json
import re
import subprocess
from pathlib import Path
from layout import shape
from stabs import Unsupported

RAW = re.compile(r'^unsigned char\s+(\w+)\[(\d+)\];', re.M)


def generate_bss(root, out, compiler, db, byname, emitter):
    source = (root / 'src/blobs/bss.c').read_text()
    preprocess = re.sub(r'^\s*#\s*include[^\n]*', '', source, flags=re.M)
    active = subprocess.run([compiler, '-target', 'arm64-apple-macos', '-DCOD2_X64=1',
                             '-ffreestanding', '-E', '-P', '-x', 'c', '-'], input=preprocess,
                            text=True, capture_output=True, check=True).stdout
    records, replacements, probe = [], {}, []
    raw_names = set()
    for match in RAW.finditer(active):
        name, extent = match[1], int(match[2])
        raw_names.add(name)
        lookup = re.sub(r'_[0-9a-f]{8}$', '', name)
        variables = byname.get(name, []) or byname.get(lookup, [])
        if not variables and name.startswith('_'):
            variables = byname.get(name[1:], [])
        choices, reasons = {}, set()
        for var in variables:
            try:
                ty = shape(db, var.type)
                if ty['size'] > extent:
                    raise Unsupported('debug type exceeds original BSS array')
                choices[json.dumps(ty, sort_keys=True)] = ty
            except (Unsupported, RecursionError) as error:
                reasons.add(str(error))
        if len(choices) == 1:
            ty = next(iter(choices.values()))
            ctype = emitter.ctype(ty)
            init = '{0}' if ty['kind'] in ('struct', 'union', 'array') else '0'
            value_bytes = ty['size']
            replacements[name] = ctype + ' ' + name + ' = ' + init + ';'
            record = dict(name=name, status='typed', ctype=ctype, bytes=extent, value_bytes=value_bytes)
            declaration = ctype + ' ' + name + ' = ' + init + ';'
            assertion = '_Static_assert(sizeof(%s) == %d, "i386 BSS type: %s");' % (ctype, value_bytes, name)
        else:
            reason = 'ambiguous static variable types' if choices else '; '.join(sorted(reasons)) or 'no matching debug variable'
            record = dict(name=name, status='fallback', bytes=extent, reason=reason)
            declaration = 'unsigned char %s[%d] = {0};' % (name, extent)
            assertion = '_Static_assert(sizeof(%s) == %d, "i386 BSS fallback: %s");' % (name, extent, name)
        records.append(record)
        probe.append('\n/* %s: %s */\n%s\n#if __SIZEOF_POINTER__ == 4\n%s\n#endif\n' %
                     (name, record.get('reason', record['status']), declaration, assertion))
    # Inventory all remaining declarations in the active x64 branch. Do not
    # reinterpret its deliberate jmp_buf, engine struct, or BSSINT choices.
    for match in re.finditer(r'^([A-Za-z_][^;\n{}]*);$', active, re.M):
        declaration = match[1]
        if declaration.startswith(('typedef ', 'extern ', '__asm')):
            continue
        match_name = re.search(r'\b(\w+)\s*(?:\[[^]]*\])*\s*$', declaration)
        if match_name and match_name[1] not in raw_names:
            records.append(dict(name=match_name[1], status='upstream_typed', declaration=declaration + ';'))
    record_byname = {r['name']: r for r in records}

    def replace(match):
        name = match[1]
        if name not in raw_names:
            return match[0]
        if name in replacements:
            # Source-copy guards make the original ILP32 declaration explicit;
            # the generated production file is only selected by COD2_X64.
            return '#if defined(COD2_X64)\n' + replacements[name] + '\n#else\n' + match[0] + '\n#endif'
        return '/* DATAGEN_FALLBACK: ' + record_byname[name]['reason'] + ' */\n' + match[0]

    text = RAW.sub(replace, source)
    include = '#define DG_ENGINE_HEADERS 1\n#include "typed_types.h"\n'
    text = text.replace('#include "common_types.h"', '#include "common_types.h"\n' + include, 1)
    banner = '/* Generated by tools/datagen/generate.py. Do not edit or commit. */\n'
    (out / 'bss_native.c').write_text(banner + text)
    (out / 'bss_probe.c').write_text(banner + '#include "typed_types.h"\n' + ''.join(probe))
    return sorted(records, key=lambda r: r['name'])
